// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMWvht3cyZUt-FhiT7tA_R524sZfGMDiQ',
    appId: '1:452232986936:web:9f38f975b35d8ecdd841cd',
    messagingSenderId: '452232986936',
    projectId: 'medicare-74c13',
    authDomain: 'medicare-74c13.firebaseapp.com',
    storageBucket: 'medicare-74c13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjxf4qO6bp3TM0zBDu5JShWajSriziziU',
    appId: '1:452232986936:android:f48a75a90d012110d841cd',
    messagingSenderId: '452232986936',
    projectId: 'medicare-74c13',
    storageBucket: 'medicare-74c13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU07jX0khfMG-pwOPjKytJjOxJeva2BIk',
    appId: '1:452232986936:ios:ed970917227ebe51d841cd',
    messagingSenderId: '452232986936',
    projectId: 'medicare-74c13',
    storageBucket: 'medicare-74c13.firebasestorage.app',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU07jX0khfMG-pwOPjKytJjOxJeva2BIk',
    appId: '1:452232986936:ios:ed970917227ebe51d841cd',
    messagingSenderId: '452232986936',
    projectId: 'medicare-74c13',
    storageBucket: 'medicare-74c13.firebasestorage.app',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMWvht3cyZUt-FhiT7tA_R524sZfGMDiQ',
    appId: '1:452232986936:web:4cca5e0e156a3e94d841cd',
    messagingSenderId: '452232986936',
    projectId: 'medicare-74c13',
    authDomain: 'medicare-74c13.firebaseapp.com',
    storageBucket: 'medicare-74c13.firebasestorage.app',
  );
}
